guru:
  jms:
    username: JMS Username defined in Yaml
    password: JMS some YML pass
    dburl: "url:db:defined:in:yaml"

#  datasource:
#    username: Oleg

---
spring:
  profiles: de

guru:
  jms:
    username: JMS for German User